### ISSUE TITLE
服务启动了，但是client打开没有反应，访问localhost:8000报404错误

### ISSUE THREAD

**Issue by bingqiang2021** [py499372727/AgentSims#1]
服务启动了，但是client打开没有反应，访问localhost:8000报404错误，不知道什么原因？

**Comment by py499372727** [comment]
This issue has been resolved through email communication, thank you for your attention.

**Comment by mindrover** [comment]
> 服务启动了，但是client打开没有反应，访问localhost:8000报404错误，不知道什么原因？

@py499372727 the same issue, how can i resolve it?
