### ISSUE TITLE
不加载默认的agent和building,也无法自己创建

### ISSUE THREAD

**Issue by Science2AI-TaoXu** [py499372727/AgentSims#3]
尝试换了centos系统和ubuntu系统都出现同样的问题

**Comment by py499372727** [comment]
Please check with the following notes:
1.If you enter the client and find no operation buttons on the left and right sides, please scale the browser appropriately for your system. For example, "command" + "+" or "-" on MacOS. If there are buttons but only the mayor or one person on the screen, try scaling the map using the button on the right side.
2.If you enter the client and find no default agent info (Alan and pH) in the agent list on the left side, and no default building info, please check the Server Terminal for any error messages.
3.If you enter the client and click on tick or mayor with no response, please check logs/tick.log for any related error messages. Also check if the cooldown parameter in app.json has been modified to a suitable value. For any other issues not mentioned, please contact us.

**Comment by Science2AI-TaoXu** [comment]
2. checked already, no error messages output;
3. logs directory is empty and has no tick.log file

**Comment by py499372727** [comment]
Could you attach the _nohub.log_ File or send the file to zhaohaoran@buaa.edu.cn. I'll try to figure it out.

**Comment by Science2AI-TaoXu** [comment]
sure, thank you so much

**Comment by lzw2000118** [comment]
> 2. checked already, no error messages output;
> 3. logs directory is empty and has no tick.log file

我遇到了相同的问题，请问您解决了吗？

**Comment by akabbks** [comment]
我也是这个问题，这是只有外皮的游戏嘛...

**Comment by py499372727** [comment]
Hello, the author of this issue has already contacted me via email and resolved this issue. The problem was with the chatGPT API call, specifically network issues and API quota limitations. I suggest troubleshooting your own deployment problems first when encountering errors, rather than criticizing others' projects. Also, this is not a game - I don't recommend trying it just for entertainment.
