### ISSUE TITLE
打开client/index.html后没有显示

### ISSUE THREAD

**Issue by chenyzh28** [py499372727/AgentSims#4]
<img width="732" alt="thumbnail_7bef8d69c1264645bd58bbda563dcc01" src="https://github.com/py499372727/AgentSims/assets/35193979/5cc4c762-d8af-48e2-bdb8-f547c81fbfd2">

**Comment by py499372727** [comment]
Is there any error in Server Terminal？

**Comment by chenyzh28** [comment]
@py499372727 No, it seems normal.
<img width="572" alt="thumbnail_fb50b7275ad9844c8ce875f6d6a83698" src="https://github.com/py499372727/AgentSims/assets/35193979/72ed0eb1-068e-4c70-ba7e-9eb2d29bf976">
eems normal

**Comment by py499372727** [comment]
Could you attach the nohub.log File or send the file to [zhaohaoran@buaa.edu.cn](mailto:zhaohaoran@buaa.edu.cn). I'll try to figure it out.

**Comment by chenyzh28** [comment]
OK, thanks, the nohup.log file it's here.
[nohup.log](https://github.com/py499372727/AgentSims/files/12391942/nohup.log)

**Comment by chenyzh28** [comment]
@py499372727 The above problem has been solved. But I cannot chat with the NPC. I send some messages to him but he responses null.
<img width="947" alt="thumbnail_ed8b3761c336a646889400463a2bd371" src="https://github.com/py499372727/AgentSims/assets/35193979/be92d909-d007-4974-a79c-5b0d0a54d1f6">

**Comment by chenyzh28** [comment]
@py499372727 I address this problem and can chat with NPCs after changing the openai api link , thanks for your work.

**Comment by py499372727** [comment]
That's good news. Thank you for your attention.
