### ISSUE TITLE
unity client 有计划开源吗？

### ISSUE THREAD

**Issue by stevensu1977** [py499372727/AgentSims#5]
unity client 有计划开源吗？

**Comment by py499372727** [comment]
We apologize that due to our limited familiarity with the Unity engine, there are no open source plans for the current version. We expect to open source the Unity client in future work (approximately one month from now). Please stay tuned for our upcoming developments.

**Comment by hugoycj** [comment]
@py499372727 Nice job! I wonder if there is any update about the source code of Unity client
