### ISSUE TITLE
WELLDONE Wallet is not initialized

### ISSUE THREAD

**Issue by jobsschang** [py499372727/AgentSims#7]
When I want to creat a new character front end said WELLDONE Wallet is not initialized

**Comment by py499372727** [comment]
Hi, could you attach the screenshot of the client when reporting error?

**Comment by jobsschang** [comment]
Hi! thank you! I solved this problem! but I met another problem which is i can not make them run a long time even I clict tick or run tick.py. i have changed the  count_limit and cooldown.

**Comment by jobsschang** [comment]
![image](https://github.com/py499372727/AgentSims/assets/106314612/ec83f4e0-f7ad-4a59-90b1-6d7a73d81c74)
